# Generated by Django 4.1.7 on 2023-04-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodule',
            name='endedDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Normal', 'Normal')], max_length=30),
        ),
    ]
